// vue-port-test-1/src/App.vue
<script setup lang="ts">
  const sessionStorageKey = 'my-session-data';
  const localStorageKey = 'my-local-data';
  const sessionStorage = window.sessionStorage;
  const localStorage = window.localStorage;
</script>

<template>
  <h1>Hello from Vue Port Test 1</h1>
  <p></p>
  <strong>Session Storage Data:</strong>
  <p></p>
  <pre>{{ sessionStorage.getItem(sessionStorageKey) }}</pre>
  <p></p>
  <strong>Local Storage Data:</strong>
  <p></p>
  <pre>{{ localStorage.getItem(localStorageKey) }}</pre>
</template>

// angular-port-test-2/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-port-test-2';

  sessionStorage = sessionStorage;
  localStorage = localStorage;

  sessionStorageKey = 'my-session-data';
  localStorageKey = 'my-local-data';
}

<h1>Hello from Angular Project 2</h1>

<strong>Session Storage Data:</strong>
<pre>{{ sessionStorage.getItem(sessionStorageKey) }}</pre>

<strong>Local Storage Data:</strong>
<pre>{{ localStorage.getItem(localStorageKey) }}</pre>
